### ISSUE TITLE
Allow to suppress drupal messages, allow to choose which cache types should be purged.

### ISSUE THREAD

**Issue by rthideaway** [BurdaMagazinOrg/module-custom_purge#2]
We need to suppress drupal messages when purging caches on node update, to not disrupt editors too much.

We also need to have a possibility to choose which cache types should be purged, since not all of our environments goes via cloudflare for example.

**Comment by rthideaway** [comment]
Hopefully this PR should fulfill those two requirements: https://github.com/BurdaMagazinOrg/module-custom_purge/pull/1

**Comment by AndreBaumeier** [comment]
merged
